# Installing Pandas

**pip install pandas**

# **Importing Pandas**

In [1]:
import pandas as pd
import numpy as np

# **Pandas**

**Pandas** is a powerful **Python library for data manipulation and analysis.** It provides easy-to-use data structures and functions to work with structured data like tabular, time series, or matrix data.

**Pandas primarily provides two data structures: Series and DataFrame.**

**Series:** A one-dimensional labeled array capable of holding any data type.

**DataFrame:** A two-dimensional labeled data structure with columns of potentially different types.

# **Pandas - Series**

**Series** in pandas is a fundamental data structure that represents a one-dimensional array of indexed data. It can hold any type of **data—integers, strings, floats, Python objects**, etc. The Series object is built on top of the NumPy array and is very similar to it but with additional capabilities like handling missing data. The indices of a pandas Series are more flexible than those in a simple NumPy array.

# Creating a Series

In [5]:
s = pd.Series([1, 3, 5, 7, 9,5.6])
print(s)

0    1.0
1    3.0
2    5.0
3    7.0
4    9.0
5    5.6
dtype: float64

In [6]:
type(s)

pandas.core.series.Series

In [12]:
s1=pd.Series([1,2,3,4,5,6,9.0,6.0,6,7,8,9,None])
print(s1)

0     1.0
1     2.0
2     3.0
3     4.0
4     5.0
5     6.0
6     9.0
7     6.0
8     6.0
9     7.0
10    8.0
11    9.0
12    NaN
dtype: float64

In [11]:
s.head()

0    1.0
1    3.0
2    5.0
3    7.0
4    9.0
dtype: float64

**Key Attributes**

**Values:** The data in the Series.

**Index:** The index (labels) of each data point.

# **Common Methods of Series**

# Descriptive Statistics

**s.describe():** Provides a quick summary of the data.

This method gives a statistical summary of the Series, including count, mean, standard deviation, minimum, maximum, and quartile values.

In [2]:
import pandas as pd

In [10]:
# Creating a Series
s = pd.Series([1, 3, 5, 7, 9])

# Descriptive statistics
print(s.describe())

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64

In [6]:
s1.describe()

count    12.000000
mean      5.500000
std       2.611165
min       1.000000
25%       3.750000
50%       6.000000
75%       7.250000
max       9.000000
dtype: float64

In [7]:
s1.info()

<class 'pandas.core.series.Series'>
RangeIndex: 13 entries, 0 to 12
Series name: None
Non-Null Count  Dtype
--------------  -----
12 non-null     float64
dtypes: float64(1)
memory usage: 232.0 bytes

**s.mean():** Computes the mean of the data.

In [8]:
# Mean of the Series
print(s1.mean())

5.5

**s.std():** Computes the standard deviation.

In [9]:
# Standard deviation of the Series
print(s1.std())

2.6111648393354674

**s.min() and s.max():** Computes the minimum and maximum values.

In [10]:
# Minimum and maximum values
print(s.min())
print(s.max())

1
9

# Data Manipulation

**s.map(func):** Applies a function to each element in the Series.

In [13]:
# Mapping function to double the values
doubled = s1.map(lambda x: x * 2)
print(doubled)

0      2.0
1      4.0
2      6.0
3      8.0
4     10.0
5     12.0
6     18.0
7     12.0
8     12.0
9     14.0
10    16.0
11    18.0
12     NaN
dtype: float64

**s.apply(func):** Similar to map, but more flexible. (Can be used Data Frames as well, where as map is only for Series)

In [15]:
# Applying a function to calculate square root
sqrt = s.apply(lambda x: x ** 0.5)
print(sqrt)

0    1.000000
1    1.732051
2    2.236068
3    2.645751
4    3.000000
dtype: float64

**s.sort_values():** Sorts the Series.

In [17]:
# Sorting the Series
sorted_s = s1.sort_values(ascending=False)
print(sorted_s)

6     9.0
11    9.0
10    8.0
9     7.0
5     6.0
7     6.0
8     6.0
4     5.0
3     4.0
2     3.0
1     2.0
0     1.0
12    NaN
dtype: float64

**s.drop(labels):** Drops specified labels from the Series.

In [15]:
s = pd.Series([1, 3, 5, 7, 9])
s

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [18]:
# Dropping the first element
dropped = s.drop([1,4],inplace=True)
print(dropped)

None

In [19]:
print(s)

0    1
2    5
3    7
dtype: int64

# Handling Missing Data

**s.isnull():** Checks for missing values, returns a Series of booleans.

In [22]:
# Checking for missing values
print(s.isnull().sum())

0

**s.notnull():** Opposite of isnull().

In [17]:
# Checking for non-null values
print(s1.notnull())

0      True
1      True
2      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12    False
dtype: bool

**s.fillna(value):** Fills missing values with a specified value.

In [24]:
import numpy as np

In [25]:
# Create a Series with missing values
s = pd.Series([1, 2, np.nan, 4, np.nan])

# Print the Series
print(s)

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [26]:
# Filling missing values with 0
filled = s.fillna(0)
print(filled)

0    1.0
1    2.0
2    0.0
3    4.0
4    0.0
dtype: float64

In [28]:
s.fillna(10,inplace=True)

In [29]:
s

0     1.0
1     2.0
2    10.0
3     4.0
4    10.0
dtype: float64

**s.dropna():** Drops all rows that contain missing values.

In [30]:
# Creating a Series with missing values
s_with_missing = pd.Series([1, 2, None, 4, 5])

# Dropping missing values
dropped_missing = s_with_missing.dropna()
print(dropped_missing)

0    1.0
1    2.0
3    4.0
4    5.0
dtype: float64

# Indexing, Slicing, and Filtering

**s.iloc[ ]:** Purely integer-location based indexing.

In [31]:
# Indexing by position
s = pd.Series([1, 3, 5, 7, 9,4,56,7,8,9,454])
print(s.iloc[0])  # First element
print(s.iloc[-1])  # Last element

1
454

**s.loc[ ]:** Label-based indexing.

In [32]:
# Indexing by label
print(s.loc[6])  # First element
print(s.loc[10])  # Last element

56
454

In [35]:
# Create a Series
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s)
# Accessing elements using iloc
print(s.iloc[0])  # Access the first element
print(s.iloc[1:3])  # Access elements at positions 1 and 2 (exclusive of 3)

# Accessing elements using loc
print(s.loc['a'])  # Access the element with index label 'a'
print(s.loc['b':'d'])  # Access elements with index labels 'b' and 'c'

a    10
b    20
c    30
d    40
dtype: int64
10
b    20
c    30
dtype: int64
10
b    20
c    30
d    40
dtype: int64

**s[s > n]:** Filters and returns elements greater than n.

In [26]:
s1

0      1.0
1      2.0
2      3.0
5      6.0
6      9.0
7      6.0
8      6.0
9      7.0
10     8.0
11     9.0
12    10.0
dtype: float64

In [27]:
# Filtering elements greater than 5 and lessthan 10
filtered = s1[(s1 > 5) &  (s1<10)]
print(filtered)

5     6.0
6     9.0
7     6.0
8     6.0
9     7.0
10    8.0
11    9.0
dtype: float64

# Aggregation

**s.sum():** Sums up the values.

In [28]:
# Sum of the Series
print(s.sum())

100

**s.cumsum():** Cumulative sum.

In [29]:
# Cumulative sum of the Series
print(s)
print(s.cumsum())

a    10
b    20
c    30
d    40
dtype: int64
a     10
b     30
c     60
d    100
dtype: int64

**s.aggregate(func):** Aggregates using one or more operations.

In [38]:
# Aggregating using multiple operations
aggregated = s.aggregate(['sum', 'mean','median','std'])
print(aggregated)

sum       100.000000
mean       25.000000
median     25.000000
std        12.909944
dtype: float64

# Creating Data Frame

In [31]:
# Define data
data = {
    'Name': ['Ganesh', 'Vignesh', 'Maheshwar', 'Naman', 'Naveen', 'Shreya', 'Varsha', 'Varun'],
    'Role': ['Founder', 'Growth Manager', 'Community Manager', 'Community Manager', 'Community Manager',
             'Course Designer', 'Course Designer', 'Public Relations Manager'],
    'Phone Number': ['111-111-1111', '222-222-2222', '333-333-3333', '444-444-4444',
                     '555-555-5555', '666-666-6666', '777-777-7777', '888-888-8888'],
    'Address': ['123, MG Road, Bangalore', '456, Brigade Road, Chennai', '789, Rajaji Nagar, Mumbai', '101, Indira Nagar, Delhi',
                '202, Koramangala, Hyderabad', '303, JP Nagar, Kolkata', '404, Electronic City, Pune', '505, HSR Layout, Ahmedabad'],
    'Blood Group': ['A+', 'B-', 'O+', 'AB+', 'A-', 'B+', 'O-', 'AB-']
}

# Create DataFrame
team_df = pd.DataFrame(data)

# Display DataFrame
team_df.head()

,Name,Role,Phone Number,Address,Blood Group
0,Ganesh,Founder,111-111-1111,"123, MG Road, Bangalore",A+
1,Vignesh,Growth Manager,222-222-2222,"456, Brigade Road, Chennai",B-
2,Maheshwar,Community Manager,333-333-3333,"789, Rajaji Nagar, Mumbai",O+
3,Naman,Community Manager,444-444-4444,"101, Indira Nagar, Delhi",AB+
4,Naveen,Community Manager,555-555-5555,"202, Koramangala, Hyderabad",A-

In [32]:
team_df

,Name,Role,Phone Number,Address,Blood Group
0,Ganesh,Founder,111-111-1111,"123, MG Road, Bangalore",A+
1,Vignesh,Growth Manager,222-222-2222,"456, Brigade Road, Chennai",B-
2,Maheshwar,Community Manager,333-333-3333,"789, Rajaji Nagar, Mumbai",O+
3,Naman,Community Manager,444-444-4444,"101, Indira Nagar, Delhi",AB+
4,Naveen,Community Manager,555-555-5555,"202, Koramangala, Hyderabad",A-
5,Shreya,Course Designer,666-666-6666,"303, JP Nagar, Kolkata",B+
6,Varsha,Course Designer,777-777-7777,"404, Electronic City, Pune",O-
7,Varun,Public Relations Manager,888-888-8888,"505, HSR Layout, Ahmedabad",AB-

# Merging Data Frames

In [33]:
# Team roles data
roles_data = {
    'Name': ['Ganesh', 'Vignesh', 'Maheshwar', 'Naman', 'Naveen', 'Shreya', 'Varsha', 'Varun'],
    'Role': ['Founder', 'Growth Manager', 'Community Manager', 'Community Manager', 'Community Manager',
             'Course Designer', 'Course Designer', 'Public Relations Manager']
}

roles_df = pd.DataFrame(roles_data)

# Contact information data
contact_data = {
    'Name': ['Ganesh', 'Vignesh', 'Maheshwar', 'Naman', 'Naveen', 'Shreya', 'Varsha', 'Varun'],
    'Phone Number': ['111-111-1111', '222-222-2222', '333-333-3333', '444-444-4444',
                     '555-555-5555', '666-666-6666', '777-777-7777', '888-888-8888'],
}

contact_df = pd.DataFrame(contact_data)

In [34]:
merged_df = pd.merge(roles_df, contact_df, on='Name')

In [35]:
merged_df

        Name                      Role  Phone Number
0     Ganesh                   Founder  111-111-1111
1    Vignesh            Growth Manager  222-222-2222
2  Maheshwar         Community Manager  333-333-3333
3      Naman         Community Manager  444-444-4444
4     Naveen         Community Manager  555-555-5555
5     Shreya           Course Designer  666-666-6666
6     Varsha           Course Designer  777-777-7777
7      Varun  Public Relations Manager  888-888-8888

In [36]:
pd.concat([roles_df, contact_df], axis=1)

        Name                      Role       Name  Phone Number
0     Ganesh                   Founder     Ganesh  111-111-1111
1    Vignesh            Growth Manager    Vignesh  222-222-2222
2  Maheshwar         Community Manager  Maheshwar  333-333-3333
3      Naman         Community Manager      Naman  444-444-4444
4     Naveen         Community Manager     Naveen  555-555-5555
5     Shreya           Course Designer     Shreya  666-666-6666
6     Varsha           Course Designer     Varsha  777-777-7777
7      Varun  Public Relations Manager      Varun  888-888-8888

In [37]:
merged_df

        Name                      Role  Phone Number
0     Ganesh                   Founder  111-111-1111
1    Vignesh            Growth Manager  222-222-2222
2  Maheshwar         Community Manager  333-333-3333
3      Naman         Community Manager  444-444-4444
4     Naveen         Community Manager  555-555-5555
5     Shreya           Course Designer  666-666-6666
6     Varsha           Course Designer  777-777-7777
7      Varun  Public Relations Manager  888-888-8888

In [39]:
import pandas as pd

# **Importing Dataset**

Importing datasets into Pandas is straightforward, and Pandas supports various file formats like csv, xlsx, json, sql etc.

In [39]:
pd.read_parquet

<function pandas.io.parquet.read_parquet(path: 'FilePath | ReadBuffer[bytes]', engine: 'str' = 'auto', columns: 'list[str] | None' = None, storage_options: 'StorageOptions | None' = None, use_nullable_dtypes: 'bool | lib.NoDefault' = <no_default>, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>, filesystem: 'Any' = None, filters: 'list[tuple] | list[list[tuple]] | None' = None, **kwargs) -> 'DataFrame'>

In [40]:
df = pd.read_csv(r"D:\OneDrive - Datavalley India Pvt Ltd\Data Analytics\Python\filmtv_movies.csv")
# Display the first few rows of the DataFrame to understand its structure and contents
df.head()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41399 entries, 0 to 41398
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   filmtv_id     41399 non-null  int64
 1   title         41399 non-null  object
 2   year          41399 non-null  int64
 3   genre         41304 non-null  object
 4   duration      41399 non-null  int64
 5   country       41389 non-null  object
 6   directors     41365 non-null  object
 7   actors        39272 non-null  object
 8   avg_vote      41399 non-null  float64
 9   critics_vote  36703 non-null  float64
 10  public_vote   41205 non-null  float64
 11  total_votes   41399 non-null  int64
 12  description   39857 non-null  object
 13  notes         18797 non-null  object
 14  humor         41399 non-null  int64
 15  rhythm        41399 non-null  int64
 16  effort        41399 non-null  int64
 17  tension       41399 non-null  int64
 18  erotism       41399 non-null  int64
dtypes: float64(3), int64(9), object(7)
memory usage: 6.0+ MB

In [42]:
df.duplicated().sum()

0

In [43]:
df.drop_duplicates()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

The dataset contains information about movies, represented in a DataFrame structure.

**filmtv_id:** A unique identifier for each movie.

**title:** The title of the movie.

**year:** The release year of the movie.

**genre:** The genre of the movie.

**duration:** The duration of the movie in minutes.

**country:** The country where the movie was produced.

**directors:** Names of the directors of the movie.

**actors:** Names of the main actors in the movie.

**avg_vote, critics_vote, public_vote:** Average ratings from different sources.

**total_votes:** Total number of votes the movie received.

**description:** A short description of the movie plot.

**notes:** Additional notes or commentary about the movie.

**humor, rhythm, effort, tension, erotism:** Various attributes rated on a scale (probably from 0 to a maximum value, representing different aspects of the movie).

# **Pandas - DataFrame**

# Properties of DataFrame

**df.head(n):**
The df.head(n) method is used to view the first n rows of the DataFrame. This is particularly useful for getting a quick snapshot of the data, especially to understand the structure and the types of data contained in each column. If you don't specify n, the default number of rows displayed is 5.

In [44]:
df.head()  # Displays the first 10 rows of the DataFrame

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

**df.tail(n):**
The df.tail(n) method is similar to df.head(n) but for the end of the DataFrame. It returns the last n rows. This is useful to see the most recent or the last few entries in your data, depending on the ordering of your dataset. Like df.head(n), the default value of n is 5 if it isn't specified.

In [45]:
df.tail()  # Displays the last 10 rows of the DataFrame

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

**df.shape:**
The df.shape attribute of a DataFrame returns a tuple representing the dimensionality of the DataFrame. The first element of the tuple is the number of rows, and the second is the number of columns. This is useful when you need to know how large the dataset is, such as when you are preprocessing data or ensuring that data manipulations have executed correctly.

In [46]:
df.shape  # Outputs: (number of rows, number of columns)

(41399, 19)

**df.columns:**
The df.columns attribute returns an Index object containing the column labels of the DataFrame. Knowing the column names is essential for accessing specific data in the DataFrame, performing analyses, and for data manipulation tasks like sorting, filtering, or applying functions to certain columns.

In [47]:
df.columns  # Lists all the column names in the DataFrame

Index(['filmtv_id', 'title', 'year', 'genre', 'duration', 'country',
       'directors', 'actors', 'avg_vote', 'critics_vote', 'public_vote',
       'total_votes', 'description', 'notes', 'humor', 'rhythm', 'effort',
       'tension', 'erotism'],
      dtype='object')

**Inspecting Data Types:** Each column in a DataFrame has a specific data type. Understanding these types is crucial for proper data manipulation

In [48]:
# Display the data types of each column
df.dtypes

filmtv_id         int64
title            object
year              int64
genre            object
duration          int64
country          object
directors        object
actors           object
avg_vote        float64
critics_vote    float64
public_vote     float64
total_votes       int64
description      object
notes            object
humor             int64
rhythm            int64
effort            int64
tension           int64
erotism           int64
dtype: object

**Summary Statistics:** For numerical data, it's useful to get a sense of their central tendency and spread

In [49]:
# Display summary statistics for numerical columns
df.describe()

,filmtv_id,year,duration,avg_vote,critics_vote,public_vote,total_votes,humor,rhythm,effort,tension,erotism
count,41399.000000,41399.000000,41399.000000,41399.000000,36703.000000,41205.000000,41399.000000,41399.000000,41399.000000,41399.000000,41399.000000,41399.000000
mean,57746.410179,1993.505302,100.537163,5.801522,5.796077,5.924135,36.986763,0.577381,1.345347,0.684847,0.919153,0.309814
std,59962.095730,23.685612,27.260962,1.403861,1.593062,1.480112,69.386853,0.899402,1.154829,1.112334,1.095410,0.645930
min,2.000000,1897.000000,41.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,15857.000000,1976.000000,90.000000,4.800000,4.670000,5.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,36266.000000,2001.000000,96.000000,5.900000,6.000000,6.000000,12.000000,0.000000,2.000000,0.000000,0.000000,0.000000
75%,70935.000000,2013.000000,107.000000,6.900000,7.000000,7.000000,36.000000,1.000000,2.000000,1.000000,2.000000,0.000000
max,232920.000000,2023.000000,1525.000000,10.000000,10.000000,10.000000,1082.000000,5.000000,5.000000,5.000000,5.000000,5.000000

# Accessing and Filtering:

**df.loc:**
The df.loc method is used for label-based indexing, meaning you can access rows and columns using their labels (i.e., index names and column names). It allows for selecting a subset of rows and columns from a DataFrame with powerful and flexible slicing, indexing, and filtering options.

In [50]:
df.head(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [45]:
# Selecting all rows and a specific column by label
titles = df.loc[1000:3000,'title']
titles

1000                     Call Me
1001     Lo chiamavano Bulldozer
1002     Un hombre llamado Noon
1003    Lo chiamavano Trinità...
1004             Claire de femme
                  ...
2996     The World of Suzie Wong
2997             Il mondo di Yor
2998               Woman's World
2999        Il mondo le condanna
3000           World in his Arms
Name: title, Length: 2001, dtype: object

In [46]:
# Selecting a range of rows and multiple columns by labels
subset = df.loc[10:2000, ['title', 'year', 'genre']]
subset

                                     title  year        genre
10               A Ghentar si muore facile  1968    Adventure
11                 Sleeping with the Enemy  1990        Drama
12                     In Bed With Madonna  1990  Documentary
13                      Bowery at Midnight  1942       Horror
14    A mezzanotte va la ronda del piacere  1975       Comedy
...                                    ...   ...          ...
1996                                Gandhi  1982    Biography
1997                       Thieves Like Us  1974        Drama
1998                     The Doberman Gang  1972     Thriller
1999                            The Racket  1952        Crime
2000                        Gangster Story  1960       Comedy

[1991 rows x 3 columns]

In [53]:
df.dtypes

filmtv_id         int64
title            object
year              int64
genre            object
duration          int64
country          object
directors        object
actors           object
avg_vote        float64
critics_vote    float64
public_vote     float64
total_votes       int64
description      object
notes            object
humor             int64
rhythm            int64
effort            int64
tension           int64
erotism           int64
dtype: object

In [50]:
df['country'].value_counts()

country
United States                           16490
Italy                                    7934
France                                   2246
Great Britain                            1946
Germany                                   963
                                        ...
Hong Kong, Japan, France, Argentina         1
East Germany, Soviet Union, Bulgaria        1
East Germany, Poland                        1
East Germany, Romania                       1
Malaysia, Singapore, China                  1
Name: count, Length: 2087, dtype: int64

In [52]:
# Conditional selection using a boolean array
dramas = df.loc[(df['genre'] == 'Comedy') & (df['avg_vote']>5.0) &(df['year']==1990)]
dramas.head()

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
144,240,Alice,1990,Comedy,106,United States,Woody Allen,"Mia Farrow, William Hurt, Joe Mantegna, Cybill...",6.7,6.70,7.0,98,"Alice is forty, with two children, a kind husb...","Allen, increasingly eyeing European cinema, th...",2,2,1,1,0
259,407,Love at Large,1990,Comedy,99,United States,Alan Rudolph,"Tom Berenger, Anne Archer, Elizabeth Perkins, ...",6.1,6.00,6.0,11,The beautiful Miss Dolan assigns investigator ...,NaN,2,3,1,2,1
374,579,L'aria serena dell'Ovest,1990,Comedy,115,Italy,Silvio Soldini,"Fabrizio Bentivoglio, Patrizia Piccinini, Anto...",7.6,8.33,7.0,44,"Four characters, very different from each othe...","A work built very well, ironic and bitter, des...",3,3,4,2,3
448,694,The Object of Beauty,1990,Comedy,102,Great Britain,Michael Lindsay-Hogg,"John Malkovich, Andie MacDowell, Lolita Davido...",5.5,6.00,5.0,8,Jack and Tina live in a luxurious London hotel...,"Some for emotional reasons, some for thirst fo...",2,2,0,1,0
783,1187,Cadillac Man,1990,Comedy,97,United States,Roger Donaldson,"Robin Williams, Tim Robbins, Pamela Reed, Fran...",5.7,5.63,6.0,37,Joey O'Brien works in a used car dealership: i...,"Praise of the seller? Maybe yes, although this...",2,2,0,1,0

In [55]:
df.loc[df['country']=='Italy']

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
6,22,A ciascuno il suo,1967,Drama,93,Italy,Elio Petri,"Gian Maria Volonté, Irene Papas, Gabriele Ferz...",7.6,7.68,7.0,139,Investigations into two murders committed in a...,"Champion of the cinema of civil commitment, El...",0,2,3,3,1
8,24,A... come assassino,1966,Thriller,80,Italy,Ray Morrison (Angelo Dorigo),"Alan Steel, Mary Arden, Sergio Ciani, Ivano Da...",5.2,3.00,7.0,5,After a man's corpse is found by his niece in ...,Approximation and mediocrity in go-go.,1,2,0,1,0
10,30,A Ghentar si muore facile,1968,Adventure,101,Italy,Leon Klimovsky,"George Hilton, Ennio Girolami, Marta Padovan, ...",4.8,4.50,5.0,3,An adventurer juggles a dictator and a group o...,NaN,0,2,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41362,229821,Enzo Jannacci Vengo anch'io,2023,Documentary,97,Italy,Giorgio Verdelli,NaN,7.8,8.00,8.0,3,Enzo Jannacci's creative musical genius is tol...,NaN,0,0,0,0,0
41363,229825,Invelle,2023,Animation,96,Italy,Simone Massi,NaN,9.0,8.50,10.0,4,1918. Zelinda is a peasant child orphaned moth...,NaN,0,0,0,0,0
41386,232132,American Moon,2017,Documentary,214,Italy,Massimo Mazzucco,"Paolo Attivissimo, Aldo Fallai, Peter Lindberg...",3.3,3.33,NaN,3,"July 20, 1969: the first images of the descent...",NaN,0,4,4,3,0
41393,232816,La stoccata vincente,2023,Biography,107,Italy,Nicola Campiotti,"Alessio Vassallo, Flavio Insinna, Elena Funari...",4.5,NaN,5.0,4,The true story of the prodigy of fencing Paolo...,Freely inspired by the book The winning fool b...,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0

In [56]:
multiple_condition = df.loc[(df['genre'] == 'Drama') & (df['avg_vote']>7.0) & (df['country']=='Italy')]
multiple_condition

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
6,22,A ciascuno il suo,1967,Drama,93,Italy,Elio Petri,"Gian Maria Volonté, Irene Papas, Gabriele Ferz...",7.6,7.68,7.0,139,Investigations into two murders committed in a...,"Champion of the cinema of civil commitment, El...",0,2,3,3,1
44,92,Accattone,1961,Drama,120,Italy,Pier Paolo Pasolini,"Franco Citti, Franca Pasut, Adriana Asti, Paol...",8.4,8.81,8.0,299,"Story of a drifter, Accattone, who drags an em...",After seeing the first dailies Federico Fellin...,1,3,3,3,2
66,126,Adua e le compagne,1960,Drama,98,Italy,Antonio Pietrangeli,"Marcello Mastroianni, Simone Signoret, Sandra ...",7.9,7.94,8.0,97,In the aftermath of the Merlin law and the con...,One of the many successful portraits of women ...,2,3,4,4,3
239,377,L'amore,1948,Drama,78,Italy,Roberto Rossellini,"Anna Magnani, Federico Fellini",7.1,7.20,7.0,49,"Film in two episodes, both focused on the grea...",Two short but intense parables on love and its...,1,1,2,2,0
525,817,I bambini ci guardano,1944,Drama,90,Italy,Vittorio De Sica,"Luciano de Ambrosis, Emilio Cigoli, Isa Pola, ...",7.6,7.50,8.0,76,"Pricò is a child left by his mother, who ran a...",Heartbreaking mélo by Vittorio De Sica. If the...,1,3,4,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40042,203797,Piccolo corpo,2021,Drama,89,Italy,Laura Samani,"Ondina Quadri, Celeste Cescutti",7.1,7.42,7.0,65,"On a small island of the Italian North East, i...",NaN,0,0,0,0,0
40333,207317,Nostalgia,2022,Drama,117,Italy,Mario Martone,"Pierfrancesco Favino, Tommaso Ragno, Francesco...",7.1,7.29,7.0,126,After living for 45 years in the Middle East a...,From the novel of the same name of Ermanno Rea.,0,0,0,0,0
40875,216029,Rapito,2023,Drama,125,Italy,Marco Bellocchio,"Paolo Pierobon, Barbara Ronchi, Fausto Russo A...",7.8,8.00,8.0,97,"The story of the Jewish child Edgardo Mortara,...",NaN,1,2,3,3,1
40936,216881,Bentu,2022,Drama,70,Italy,Salvatore Mereu,"Giuseppe Cuccu, Giovanni Porcu",8.5,8.00,9.0,3,"Raffaele sleeps in the countryside, to supervi...",NaN,0,0,0,0,0
41168,220967,Come pecore in mezzo ai lupi,2023,Drama,100,Italy,Lyda Patitucci,"Isabella Ragonese, Andrea Arcangeli, Clara Ponsot",7.3,7.50,7.0,10,A policeman infiltrated in a criminal band is ...,NaN,0,0,0,0,0

**df.iloc:**
While df.loc uses labels for indexing, df.iloc allows for integer-based indexing. You use df.iloc to access rows and columns by their integer positions, which makes it useful when you need to access data by its position in the DataFrame.

In [57]:
df.head(5)

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0

In [58]:
# Selecting a single row from the DataFrame
single_row = df.iloc[10]
single_row

filmtv_id                                                      30
title                                   A Ghentar si muore facile
year                                                         1968
genre                                                   Adventure
duration                                                      101
country                                                     Italy
directors                                          Leon Klimovsky
actors          George Hilton, Ennio Girolami, Marta Padovan, ...
avg_vote                                                      4.8
critics_vote                                                  4.5
public_vote                                                   5.0
total_votes                                                     3
description     An adventurer juggles a dictator and a group o...
notes                                                         NaN
humor                                                           0
rhythm                                                          2
effort                                                          0
tension                                                         1
erotism                                                         0
Name: 10, dtype: object

In [59]:
# Selecting a specific row and columns by integer indices
specific_data = df.iloc[10, [4,5,6,7]]  # row at index 10 and columns at indices 1, 2, and 3
specific_data

duration                                                   101
country                                                  Italy
directors                                       Leon Klimovsky
actors       George Hilton, Ennio Girolami, Marta Padovan, ...
Name: 10, dtype: object

In [60]:
# Slicing to get multiple rows and columns
multi_slice = df.iloc[10:15, 0:5]  # Rows 10 to 14 and columns 0 to 3
multi_slice

,filmtv_id,title,year,genre,duration
10,30,A Ghentar si muore facile,1968,Adventure,101
11,32,Sleeping with the Enemy,1990,Drama,96
12,34,In Bed With Madonna,1990,Documentary,111
13,36,Bowery at Midnight,1942,Horror,62
14,37,A mezzanotte va la ronda del piacere,1975,Comedy,100

**df.at:**
df.at is designed to access a single value for a row/column label pair. It is very similar to df.loc for accessing scalar values but is optimized for faster access when you only need to get or set a single value in a DataFrame.

In [58]:
# Access a specific single value using row label and column name
title_of_first_movie = df.at[100, 'title']
title_of_first_movie

'Across the Pacific'

**Filtering Based on Criteria:**
Filtering data based on specific criteria is a common operation in data analysis. Pandas provides several methods to perform these operations, often using boolean indexing.

In [62]:
# Filter movies released after 2010
recent_movies = df[df['year'] > 2010]
recent_movies

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
22817,39955,The Tree of Life,2011,Drama,138,United States,Terrence Malick,"Brad Pitt, Sean Penn, Jessica Chastain, Tye Sh...",7.4,7.43,7.0,476,"Jack, an eleven-year-old boy, lives in the Mid...","Beauty passes through cinema: the director, as...",0,2,4,2,0
23725,41448,Season of the Witch,2011,Adventure,95,United States,Dominic Sena,"Nicolas Cage, Claire Foy, Ron Perlman, Stephen...",4.3,4.13,4.0,153,"During the fourteenth century, when the black ...",Thrown to the wind the attempts to build a bar...,1,2,1,3,0
24186,42398,Restless,2011,Drama,95,United States,Gus Van Sant,"Mia Wasikowska, Schuyler Fisk, Jane Adams, Lus...",6.9,6.59,7.0,151,Enoch is a 17-year-old who lost both parents a...,The director of Last Days returns to spy on th...,2,2,3,1,0
24426,42847,Qualunquemente,2011,Grotesque,96,Italy,Giulio Manfredonia,"Antonio Albanese, Sergio Rubini, Lorenza Indov...",5.6,5.65,6.0,291,Cetto La Qualunque (Albanese) returns to Italy...,The grotesque and at times effective mask rema...,4,3,3,1,1
24427,42848,Una sconfinata giovinezza,2011,Drama,98,Italy,Pupi Avati,"Fabrizio Bentivoglio, Francesca Neri, Serena G...",6.7,6.60,7.0,95,Lino Settembre and his wife Chicca lead a peac...,"Written with the taste of a novelist's plot, i...",2,2,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [63]:
# Movies with a high public vote and specific genre
highly_rated_thrillers = df[(df['public_vote'] >= 8) & (df['genre'] == 'Thriller')]
highly_rated_thrillers

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
21,54,Johnny O'Clock,1947,Thriller,95,United States,Robert Rossen,"Dick Powell, Evelyn Keyes, Lee J. Cobb, Ellen ...",7.8,8.00,8.0,20,Johnny O'Clock (Powell) is a minority partner ...,Columbia took advantage of Dick Powell's recen...,1,3,1,3,1
27,67,You'll Like My Mother,1973,Thriller,94,United States,Lamont Johnson,"Patty Duke, Rosemary Murphy, Richard Thomas, S...",7.8,8.00,8.0,6,"After her husband's death, Francesca decides t...",Specialist Lamont Johnson has built an effecti...,0,3,1,3,0
140,236,Time Without Pity,1956,Thriller,88,Great Britain,Joseph Losey,"Michael Redgrave, Ann Todd, Peter Cushing, Joa...",7.9,8.00,8.0,16,Alec Graham was sentenced to death for killing...,Emigrated to Great Britain after being blackli...,0,3,2,3,0
183,296,Strangers on a Train,1951,Thriller,96,United States,Alfred Hitchcock,"Farley Granger, Robert Walker, Ruth Roman, Leo...",8.4,8.66,8.0,258,Guy Haines is a successful tennis player with ...,"Patricia Highsmith's first novel, that of the ...",1,2,2,4,0
302,478,Gaslight,1944,Thriller,109,United States,George Cukor,"Ingrid Bergman, Charles Boyer, Joseph Cotten, ...",7.8,7.86,8.0,94,"Paula married Gregory, who long ago strangled ...","Nice ""gothic"" melodrama by George Cukor. The m...",2,4,3,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40950,216918,Aru otoko,2022,Thriller,121,Japan,Kei Ishikawa,"Satoshi Tsumabuki, Sakura Andô, Masataka Kubot...",7.3,7.00,8.0,3,Akira works as a lawyer and one day he meets a...,NaN,0,0,0,0,0
41118,220183,The Other Child,2022,Thriller,114,South Korea,Jin-young Kim,"Kim Min-Jae, Hyo-ju Park",5.3,3.00,8.0,3,The members of a family deeply likes the disap...,NaN,0,0,0,0,0
41200,221403,Anatomie d'une chute,2023,Thriller,151,France,Justine Triet,"Sandra Hüller, Samuel Theis, Swann Arlaud, Jeh...",7.3,7.00,8.0,4,"Samuel is found dead, buried in the snow outsi...",NaN,0,0,0,0,0
41218,221890,Ming On,2022,Thriller,109,Hong Kong,Soi Cheang,"Ka-Tung Lam, Charm Man Chan, Wing-Sze Ng, Lok ...",7.8,8.00,8.0,4,"A master of fortune teller (Gordon Lam), very ...",NaN,0,0,0,0,0
41246,223251,Twisted Nerve,1968,Thriller,112,Great Britain,Roy Boulting,"Hayley Mills, Hywel Bennett, Billie Whitelaw, ...",7.5,7.00,8.0,3,Martin Durnley (Hywel Bennett) is a twenty yea...,NaN,0,0,0,0,0

In [64]:
# Movies from a specific country
us_movies = df[df['country'] == 'United States']
us_movies

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
7,23,Dead-Bang,1989,Crime,109,United States,John Frankenheimer,"Don Johnson, Penelope Ann Miller, William Fors...",6.0,6.00,6.0,27,"In the throes of a double murder, Jerry Beck, ...",When it comes to talking about mysterious plot...,0,2,0,2,1
9,26,At Close Range,1986,Drama,115,United States,James Foley,"Christopher Walken, Sean Penn, Chris Penn, Mar...",7.5,7.64,7.0,90,Young Brad (Penn) lives with his grandmother a...,"Powerful and brutal thriller, second work by J...",1,3,2,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41377,231044,Shelter,2023,Thriller,91,United States,Anthony Nardolillo,"Cam Gigandet, Jaina Lee Ortiz, Lisa Vidal, Car...",3.7,4.00,3.0,7,"Annabel, leader of a secret organization engag...",NaN,1,1,1,1,0
41382,231556,To End All War: Oppenheimer & the Atomic Bomb,2023,Documentary,87,United States,Christopher Cassel,"J. Robert Oppenheimer, Kai Bird, Ellen Bradbur...",6.6,5.00,8.0,8,"The arrogance, genius and determination of a m...",NaN,0,0,0,0,0
41384,232066,Hostage House,2021,Horror,85,United States,David Benullo,"Jennifer Taylor, Justin C. Schilling, Julia Te...",4.8,NaN,5.0,4,An ambitious real estate agent and his daughte...,NaN,0,0,0,0,0
41385,232101,Fear the Night,2023,Horror,92,United States,Neil LaBute,"Maggie Q, Ito Aghayere, Philip Burke, James Ca...",3.5,3.00,4.0,5,Tes is a veteran of the war in Iraq invited to...,NaN,0,0,0,0,0
41391,232755,Organ Trail,2023,Western,112,United States,Michael Patrick Jann,"Zoé De Grand Maison, Mather Zickel, Lisa LoCic...",5.0,5.50,5.0,8,The young abigale Archer is located alone in M...,NaN,0,0,0,0,0

# Updating Rows and Columns

**df.drop:**
The .drop() method in pandas is used to remove rows or columns from a DataFrame. Its primary purpose is to drop specified labels from rows or columns.

**Parameters:**

**labels:** The row or column labels to drop.

**axis:** Specifies whether the labels refer to rows (axis=0) or columns (axis=1). By default, it's 0 (rows).

**index or columns:** An alternative way to specify the labels to drop, instead of using the labels parameter. It is equivalent to specifying axis=0 (for index) or axis=1 (for columns).

**inplace:** If True, the operation is done in place, meaning it modifies the DataFrame directly and returns None. If False or not specified, it returns a new DataFrame with the specified labels dropped.

In [65]:
df.drop(labels='title',axis=1)

,filmtv_id,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [66]:
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

**Using apply Function:**
The apply function allows you to apply a function along an axis of the DataFrame.

In [60]:
df['length_category'] = df['duration'].apply(lambda x: 'Long' if x > 120 else 'Short')
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism,length_category
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Short
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,Short
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Short
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Short
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Short
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Short
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,Short
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Short
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Short

In [61]:
df['length_category'].value_counts()

length_category
Short    37137
Long      4262
Name: count, dtype: int64

In [68]:
df['old_new'] = df['year'].apply(lambda x: 'New' if x > 2000 else 'old')
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,total_votes,description,notes,humor,rhythm,effort,tension,erotism,length_category,old_new
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Short,old
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,Short,old
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Short,old
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Short,old
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,Short,old
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Short,New
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Short,New
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,Short,New
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Short,New
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Short,New

In [69]:
# Create a DataFrame with multiple Series
data = {
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
}
num_data = pd.DataFrame(data)

In [70]:
num_data

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

**Updating Using map or replace:**
You can update a column based on a mapping dictionary or replace values.

In [71]:
df['genre'].map({'Drama': 'Drama Film', 'Comedy': 'Comedy Film'}) # Mapping existing values to new ones

0                NaN
1         Drama Film
2                NaN
3        Comedy Film
4        Comedy Film
            ...
41394            NaN
41395    Comedy Film
41396            NaN
41397            NaN
41398            NaN
Name: genre, Length: 41399, dtype: object

In [72]:
df['country'].replace('USA', 'United States', inplace=True) # Replacing specific values
df

C:\Users\marut\AppData\Local\Temp\ipykernel_13988\2704215411.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['country'].replace('USA', 'United States', inplace=True) # Replacing specific values

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,total_votes,description,notes,humor,rhythm,effort,tension,erotism,length_category,old_new
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Short,old
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,Short,old
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Short,old
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Short,old
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,Short,old
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Short,New
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Short,New
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,Short,New
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Short,New
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Short,New

**Adding New Columns Based on Calculations:**
You can create new columns based on calculations from existing columns.

In [ ]:
df['title_year'] = df['title'] + "(" + df['year'].astype(str) + ")" # Creating a new column by combining existing columns
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,description,notes,humor,rhythm,effort,tension,erotism,length_category,old_new,title_year
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Short,old,Bugs Bunny's Third Movie: 1001 Rabbit Tales(1982)
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,Short,old,18 anni tra una settimana(1991)
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Short,old,Ride a Wild Pony(1976)
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Short,old,Diner(1982)
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,Short,old,A che servono questi quattrini?(1942)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Short,New,Gold Digger Killer(2021)
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Short,New,Addio al nubilato 2(2023)
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,A team building conference organized for a gro...,NaN,0,0,0,0,0,Short,New,Konferensen(2023)
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Short,New,Ballelina(2023)
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Short,New,Invitación a un Asesinato(2023)

In [74]:
df['total_votes'] = df['avg_vote'] + df['critics_vote']

In [77]:
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,description,notes,humor,rhythm,effort,tension,erotism,length_category,old_new,title_year
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Short,old,Bugs Bunny's Third Movie: 1001 Rabbit Tales(1982)
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,Short,old,18 anni tra una settimana(1991)
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Short,old,Ride a Wild Pony(1976)
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Short,old,Diner(1982)
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,Short,old,A che servono questi quattrini?(1942)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Short,New,Gold Digger Killer(2021)
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Short,New,Addio al nubilato 2(2023)
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,A team building conference organized for a gro...,NaN,0,0,0,0,0,Short,New,Konferensen(2023)
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Short,New,Ballelina(2023)
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Short,New,Invitación a un Asesinato(2023)

# Changing the name of Index
Pandas allows you to rename the index of a DataFrame or Series, which can help in making the index more informative or aligning it with new data requirements.

**Renaming the Index of a DataFrame:**

In [78]:
df.index.names = ['movie_num']  # Renames the index to 'movie_id'

In [63]:
df.index=df['filmtv_id']

In [64]:
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism,length_category
filmtv_id,,,,,,,,,,,,,,,,,,,,
2,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Short
3,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,Short
17,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Short
18,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Short
20,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232817,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Short
232893,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Short
232915,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,Short
232919,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Short
232920,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Short

**Renaming Column Indexes:**

In [77]:
df.rename(columns={'year': 'release_year', 'title': 'movie_title'}, inplace=True)
df

,filmtv_id,movie_title,release_year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,description,notes,humor,rhythm,effort,tension,erotism,length_category,old_new,title_year
movie_num,,,,,,,,,,,,,,,,,,,,,
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,Short,old,Bugs Bunny's Third Movie: 1001 Rabbit Tales (1...
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,Short,old,18 anni tra una settimana (1991)
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,Short,old,Ride a Wild Pony (1976)
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,Short,old,Diner (1982)
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,Short,old,A che servono questi quattrini? (1942)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,Short,New,Gold Digger Killer (2021)
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,Short,New,Addio al nubilato 2 (2023)
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,A team building conference organized for a gro...,NaN,0,0,0,0,0,Short,New,Konferensen (2023)
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,Short,New,Ballelina (2023)
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,Short,New,Invitación a un Asesinato (2023)

In [84]:
df['genre'].value_counts()

genre
Drama              12003
Comedy              9225
Thriller            3701
Horror              2431
Action              2155
Documentary         2051
Adventure           1524
Western             1146
Animation           1076
Romantic             980
Sci-Fi               905
Biography            685
Fantasy              503
Crime                466
Musical              428
War                  405
Grotesque            243
Spy                  240
Noir                 238
Erotico              235
Sperimental          162
History              138
Mélo                 104
Super-hero            83
Mythology             66
Gangster              56
Biblical              38
Sport                  7
Short Movie            6
Stand-up Comedy        4
Name: count, dtype: int64

# Grouping Data:
Grouping data is a powerful way to perform segment-wise analysis and break down the dataset into chunks based on some criteria.

In [95]:
genre_groups = df.groupby('genre') # Groups the data by the 'genre' column
genre_groups

In [96]:
for genre, group_data in genre_groups:
    print(f"Genre: {genre}")
    print(group_data)
    # print()

Genre: Action
           filmtv_id                 title  year   genre  duration  \
movie_num
15                38          Mr. Majestyk  1974  Action       105
16                45          Warning Sign  1985  Action        99
109              193           Airport '77  1977  Action       110
342              530   Wings of the Apache  1990  Action        86
369              574  Geheimcode Wildgänse  1985  Action        93
...              ...                   ...   ...     ...       ...
41308         225561    Tin joek yau ching  1990  Action        87
41314         226116          Blood & Gold  2023  Action       100
41337         228408          Kung Fu Girl  2021  Action        98
41343         229097               Hit Man  2023  Action       113
41378         231061            Sentinelle  2023  Action        99

                 country                         directors  \
movie_num
15         United States                 Richard Fleischer
16         United States                       Hal Barwood
109        United States                     Jerry Jameson
342        United States                       David Green
369                Italy                Antonio Margheriti
...                  ...                               ...
41308          Hong Kong                        Benny Chan
41314            Germany                   Peter Thorwarth
41337      United States           Devon Downs, Kenny Gage
41343      United States                 Richard Linklater
41378             France  Hugo Benamozig, David Caviglioli

                                                      actors  avg_vote  \
movie_num
15         Charles Bronson, Linda Cristal, Al Lettieri, L...       6.2
16         Sam Waterston, Kathleen Quinlan, Yaphet Kotto,...       4.8
109        Jack Lemmon, James Stewart, Lee Grant, Brenda ...       4.7
342        Nicolas Cage, Sean Young, Tommy Lee Jones, Dal...       4.6
369        Lewis Collins, Lee Van Cleef, Ernest Borgnine,...       4.9
...                                                      ...       ...
41308      Andy Lau, Chien-lien Wu, Man-Tat Ng, Kwong-Leu...       7.5
41314      Jördis Triebel, Alexander Scheer, Robert Maase...       6.1
41337      Danny Kwok-Kwan Chan, Yixi Tao, Shuting Li, Xi...       4.5
41343      Adria Arjona, Glen Powell, Retta, Austin Ameli...       7.1
41378      Jonathan Cohen, Emmanuelle Bercot, Raphaël Que...       4.0

           critics_vote  ...  \
movie_num                ...
15                 5.71  ...
16                 4.00  ...
109                3.33  ...
342                4.00  ...
369                3.50  ...
...                 ...  ...
41308              7.00  ...
41314              5.67  ...
41337               NaN  ...
41343              7.00  ...
41378               NaN  ...

                                                 description  \
movie_num
15         A veteran of Vietnam, Vince (Bronson) grows me...
16         Inside the Biotek laboratory, a renowned and r...
109        An elderly billionaire, on the occasion of an ...
342        Jake Preston, a helicopter pilot, is called to...
369        Captain Wesley (Lewis Collins), whose son died...
...                                                      ...
41308      During a bank robbery, the driver designated f...
41314      Spring of 1945, the last days of the Second Wo...
41337      The twelve year old Lisa suffers from the scho...
41343      Gary Johnson, police investigator, plays under...
41378      François Sentinelle leads a double life. Durin...

                                                       notes humor rhythm  \
movie_num
15         Cliché screenplay (by Elmore Leonard) tailored...     0      4
16         It is a film that mixes "The invasion of the b...     0      2
109        The film is yet another variation on the catas...     0      2
342        Nothing to say about Nicolas Cage as a drug ag...     1      2
369                                                      NaN     0      2
...                                                      ...   ...    ...
41308                                                    NaN     0      0
41314                                                    NaN     0      0
41337                                                    NaN     0      0
41343                                                    NaN     0      0
41378                                                    NaN     0      0

           effort  tension  erotism  length_category  old_new  \
movie_num
15              3        3        0            Short      old
16              1        1        0            Short      old
109             0        1        0            Short      old
342             0        1        1            Short      old
369             0        2        0            Short      old
...           ...      ...      ...              ...      ...
41308           0        0        0            Short      old
41314           0        0        0            Short      New
41337           0        0        0            Short      New
41343           0        0        0            Short      New
41378           0        0        0            Short      New

                           title_year
movie_num
15                 Mr. Majestyk(1974)
16                 Warning Sign(1985)
109                 Airport '77(1977)
342         Wings of the Apache(1990)
369        Geheimcode Wildgänse(1985)
...                               ...
41308        Tin joek yau ching(1990)
41314              Blood & Gold(2023)
41337              Kung Fu Girl(2021)
41343                   Hit Man(2023)
41378                Sentinelle(2023)

[2155 rows x 22 columns]
Genre: Adventure
           filmtv_id                             title  year      genre  \
movie_num
10                30         A Ghentar si muore facile  1968  Adventure
20                53                A qualsiasi prezzo  1968  Adventure
33                74                          The Deep  1977  Adventure
82               145                    Africa Express  1975  Adventure
83               146               Africa sotto i mari  1952  Adventure
...              ...                               ...   ...        ...
41222         222074                   We Have a Ghost  2023  Adventure
41230         222398          Tremors: Shrieker Island  2020  Adventure
41274         224588             Knights of the Zodiac  2023  Adventure
41293         225497  Coast Guard Malaysia: Ops Helang  2023  Adventure
41330         227960                     Hidden Strike  2023  Adventure

           duration                        country           directors  \
movie_num
10              101                          Italy      Leon Klimovsky
20               94                          Italy     Emilio Miraglia
33              130                  United States         Peter Yates
82               95                          Italy        Michele Lupo
83               95                          Italy   Giovanni Roccardi
...             ...                            ...                 ...
41222           126                  United States  Christopher Landon
41230           103                  United States    Don Michael Paul
41274           112  Japan, Hungary, United States     Tomasz Baginski
41293            90                       Malaysia          Pitt Hanif
41330           102           China, United States         Scott Waugh

                                                      actors  avg_vote  \
movie_num
10         George Hilton, Ennio Girolami, Marta Padovan, ...       4.8
20         Walter Pidgeon, Ira Fürstenberg, Klaus Kinski,...       3.8
33         Nick Nolte, Jacqueline Bisset, Robert Shaw, El...       5.3
82         Giuliano Gemma, Ursula Andress, Jack Palance, ...       5.1
83         Sophia Loren, Stephen Barclay, Umberto Melnati...       4.1
...                                                      ...       ...
41222      Jennifer Coolidge, David Harbour, Anthony Mack...       6.2
41230      Michael Gross, Jon Heder, Richard Brake, Carol...       5.6
41274      Famke Janssen, Sean Bean, Madison Iseman, Mark...       3.4
41293      Saharul Ridzwan, Julia Farhana Marin, Sabri Yu...       3.5
41330      Jackie Chan, John Cena, Pilou Asbæk, Rachael H...       6.0

           critics_vote  ...  \
movie_num                ...
10                 4.50  ...
20                 4.00  ...
33                 4.88  ...
82                 5.50  ...
83                 4.00  ...
...                 ...  ...
41222              6.00  ...
41230              5.00  ...
41274              3.00  ...
41293              3.00  ...
41330               NaN  ...

                                                 description  \
movie_num
10         An adventurer juggles a dictator and a group o...
20         The holidays of Professor Cummings, an illustr...
33         A boy and a girl, passionate divers, dive off ...
82         John Baxter (Gemma) has been working in Africa...
83         In the Red Sea, a group of men is engaged in a...
...                                                      ...
41222      Kevin and his family suddenly become famous on...
41230      The adventurous entrepreneur Bill - together w...
41274      When a goddess of the war reincarnates in the ...
41293      Hafiz, the Malaysian Coast Guard officer, cele...
41330      In the near future, a group of civilians is fo...

                                                       notes humor rhythm  \
movie_num
10                                                       NaN     0      2
20         Although Emilio Miraglia is blind (in cinemati...     1      2
33         Not very exciting, but the underwater scenes a...     1      2
82         The film had a notable success with the public...     1      2
83         Except for the presence of Sophia Loren, the b...     0      1
...                                                      ...   ...    ...
41222                                                    NaN     0      0
41230                                                    NaN     0      0
41274                                                    NaN     1      1
41293                                                    NaN     0      0
41330                                                    NaN     0      0

           effort  tension  erotism  length_category  old_new  \
movie_num
10              0        1        0            Short      old
20              0        1        1            Short      old
33              1        2        1             Long      old
82              0        1        1            Short      old
83              0        1        2            Short      old
...           ...      ...      ...              ...      ...
41222           0        0        0             Long      New
41230           0        0        0            Short      New
41274           0        0        0            Short      New
41293           0        0        0            Short      New
41330           0        0        0            Short      New

                                       title_year
movie_num
10                A Ghentar si muore facile(1968)
20                       A qualsiasi prezzo(1968)
33                                 The Deep(1977)
82                           Africa Express(1975)
83                      Africa sotto i mari(1952)
...                                           ...
41222                       We Have a Ghost(2023)
41230              Tremors: Shrieker Island(2020)
41274                 Knights of the Zodiac(2023)
41293      Coast Guard Malaysia: Ops Helang(2023)
41330                         Hidden Strike(2023)

[1524 rows x 22 columns]
Genre: Animation
           filmtv_id                                        title  year  \
movie_num
0                  2  Bugs Bunny's Third Movie: 1001 Rabbit Tales  1982
159              260                         The Land Before Time  1988
167              271                           Allegro non troppo  1977
435              679                 Asterix et le coup de menhir  1989
715             1093                           The Secret Of Nimh  1982
...              ...                                          ...   ...
41256         223768  Teenage Mutant Ninja Turtles: Mutant Mayhem  2023
41257         223769                          The First Slam Dunk  2022
41266         224224                 Ruby Gillman, Teenage Kraken  2023
41348         229395                  Lonely Castle in the Mirror  2022
41363         229825                                      Invelle  2023

               genre  duration        country  \
movie_num
0          Animation        76  United States
159        Animation        79  United States
167        Animation        85          Italy
435        Animation        81         France
715        Animation        82  United States
...              ...       ...            ...
41256      Animation        99  United States
41257      Animation       124          Japan
41266      Animation        91  United States
41348      Animation       116          Japan
41363      Animation        96          Italy

                                      directors  \
movie_num
0          David Detiege, Art Davis, Bill Perez
159                                   Don Bluth
167                              Bruno Bozzetto
435                            Philippe Grimond
715                                   Don Bluth
...                                         ...
41256                   Jeff Rowe, Kyler Spears
41257            Takehiko Inoue, Yasuyuki Ebara
41266                              Kirk DeMicco
41348           Keiichi Hara, Takakazu Nagatomo
41363                              Simone Massi

                                                      actors  avg_vote  \
movie_num
0                                                        NaN       7.7
159                                                      NaN       7.4
167        Maurizio Nichetti, Maurizio Micheli, Maria Lui...       7.6
435                                                      NaN       6.8
715                                                      NaN       8.2
...                                                      ...       ...
41256                                                    NaN       6.4
41257                                                    NaN       8.0
41266                                                    NaN       6.0
41348                                                    NaN       6.7
41363                                                    NaN       9.0

           critics_vote  ...  \
movie_num                ...
0                  8.00  ...
159                7.50  ...
167                7.71  ...
435                6.67  ...
715                8.50  ...
...                 ...  ...
41256              6.50  ...
41257               NaN  ...
41266              7.00  ...
41348              6.50  ...
41363              8.50  ...

                                                 description  \
movie_num
0          With two protruding front teeth, a slightly sl...
159        A group of herbivorous dinosaurs of the "Colli...
167        A director wants to make an animated film base...
435        In Gaul subjugated by the Romans only the vill...
715        Brisby, a widowed mouse, lives in a field with...
...                                                      ...
41256      After years spent in the sewers hiding from hu...
41257      Ryota Miyagi has an older, sota, three -year -...
41266      A shy teenager discovers that he comes from a ...
41348      In a quiet district of Tokyo, seven students j...
41363      1918. Zelinda is a peasant child orphaned moth...

                                                       notes humor rhythm  \
movie_num
0          These are many small independent stories, whic...     3      3
159        With Ralph Bakshi, Don Bluth (who actually cut...     3      3
167        Debussy's "Prelude to the afternoon of a faun"...     2      3
435                                                      NaN     3      3
715        After a long experience at Disney, Don Bluth w...     2      2
...                                                      ...   ...    ...
41256                                                    NaN     0      0
41257             Based on Takehiko Inoue's Slam Dunk manga.     0      0
41266                                                    NaN     0      0
41348                                                    NaN     0      0
41363                                                    NaN     0      0

           effort  tension  erotism  length_category  old_new  \
movie_num
0               0        0        0            Short      old
159             0        1        0            Short      old
167             2        0        0            Short      old
435             0        0        0            Short      old
715             0        2        0            Short      old
...           ...      ...      ...              ...      ...
41256           0        0        0            Short      New
41257           0        0        0             Long      New
41266           0        0        0            Short      New
41348           1        1        1            Short      New
41363           0        0        0            Short      New

                                                  title_year
movie_num
0          Bugs Bunny's Third Movie: 1001 Rabbit Tales(1982)
159                               The Land Before Time(1988)
167                                 Allegro non troppo(1977)
435                       Asterix et le coup de menhir(1989)
715                                 The Secret Of Nimh(1982)
...                                                      ...
41256      Teenage Mutant Ninja Turtles: Mutant Mayhem(2023)
41257                              The First Slam Dunk(2022)
41266                     Ruby Gillman, Teenage Kraken(2023)
41348                      Lonely Castle in the Mirror(2022)
41363                                          Invelle(2023)

[1076 rows x 22 columns]
Genre: Biblical
           filmtv_id                               title  year     genre  \
movie_num
615              942                             Ben Hur  1959  Biblical
1419            2119                The Ten Commandments  1956  Biblical
1697            2531                     Erode il Grande  1958  Biblical
2114            3151                 Giuditta e Oloferne  1958  Biblical
2124            3167       Giuseppe venduto dai fratelli  1961  Biblical
2863            4274                           Il Messia  1975  Biblical
3563            5347        The Greatest Story Ever Told  1965  Biblical
3896            5854                   The King of Kings  1961  Biblical
4453            6677                 La spada e la croce  1959  Biblical
4549            6836                   The Story of Ruth  1960  Biblical
4919            7372                            The Robe  1953  Biblical
5940            9031                   Solomon and Sheba  1959  Biblical
6826           10368                       David e Golia  1959  Biblical
8392           12762  Genesi - La Creazione e il Diluvio  1994  Biblical
8434           12825                       Ester e il re  1960  Biblical
10942          16849                              Esther  1985  Biblical
11573          17935                        Il quarto re  1997  Biblical
12595          19554                     Maria Maddalena  2000  Biblical
13469          21090                               Giuda  2000  Biblical
13493          21135                             Tommaso  2001  Biblical
13955          21910                Giuseppe di Nazareth  1999  Biblical
15262          24080          San Giovanni. L'Apocalisse  2002  Biblical

In [80]:
year_genre_groups = df.groupby(['release_year', 'genre'])  # Groups by year and genre

# Aggregation

After grouping, you might want to perform aggregation operations like sum, mean, count, etc., to summarize the data.

In [98]:
# Simple Aggregation - Calculating the Average
avg_duration_by_genre = df.groupby('genre')['duration'].mean()  # Average duration per genre
print(avg_duration_by_genre)

genre
Action             101.682599
Adventure          102.870079
Animation           88.925651
Biblical           137.210526
Biography          120.602920
Comedy              97.881409
Crime               98.939914
Documentary         92.641638
Drama              105.271266
Erotico             90.893617
Fantasy            105.612326
Gangster           117.803571
Grotesque           99.851852
History            127.159420
Horror              92.603867
Musical            106.240654
Mythology           97.969697
Mélo               107.836538
Noir                98.428571
Romantic            94.778571
Sci-Fi             102.097238
Short Movie        210.500000
Sperimental         97.716049
Sport               95.428571
Spy                105.333333
Stand-up Comedy     73.000000
Super-hero         121.855422
Thriller            97.957849
War                111.306173
Western             95.800175
Name: duration, dtype: float64

In [ ]:
import numpy as np

In [65]:
df.columns

Index(['filmtv_id', 'title', 'year', 'genre', 'duration', 'country',
       'directors', 'actors', 'avg_vote', 'critics_vote', 'public_vote',
       'total_votes', 'description', 'notes', 'humor', 'rhythm', 'effort',
       'tension', 'erotism', 'length_category'],
      dtype='object')

In [67]:
# Multiple Aggregations on a Single Column
stats_by_genre = df.groupby('year')['avg_vote'].agg([np.mean, np.std, np.min, np.max])
print(stats_by_genre)

          mean       std  min  max
year
1897  6.200000       NaN  6.2  6.2
1909  7.700000       NaN  7.7  7.7
1910  6.800000       NaN  6.8  6.8
1911  6.975000  1.164403  5.3  8.0
1913  7.414286  0.414039  6.8  7.9
...        ...       ...  ...  ...
2019  5.540554  1.274514  1.0  8.7
2020  5.511251  1.198222  1.3  8.8
2021  5.476206  1.231232  1.3  8.8
2022  5.658466  1.199026  1.4  8.8
2023  5.746457  1.265648  1.7  9.0

[115 rows x 4 columns]

C:\Users\marut\AppData\Local\Temp\ipykernel_21360\4110596536.py:2: FutureWarning: The provided callable <function mean at 0x0000023BF2FB3AC0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  stats_by_genre = df.groupby('year')['avg_vote'].agg([np.mean, np.std, np.min, np.max])
C:\Users\marut\AppData\Local\Temp\ipykernel_21360\4110596536.py:2: FutureWarning: The provided callable <function std at 0x0000023BF2FB3BE0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  stats_by_genre = df.groupby('year')['avg_vote'].agg([np.mean, np.std, np.min, np.max])
C:\Users\marut\AppData\Local\Temp\ipykernel_21360\4110596536.py:2: FutureWarning: The provided callable <function min at 0x0000023BF2FB32E0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  stats_by_genre = df.groupby('year')['avg_vote'].agg([np.mean, np.std, np.min, np.max])
C:\Users\marut\AppData\Local\Temp\ipykernel_21360\4110596536.py:2: FutureWarning: The provided callable <function max at 0x0000023BF2FB31C0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  stats_by_genre = df.groupby('year')['avg_vote'].agg([np.mean, np.std, np.min, np.max])

**Aggregating Without Grouping:**
Sometimes, you may want to perform aggregations without the need to group the data.

In [100]:
# Overall Summary Statistics
overall_stats = df[['duration', 'avg_vote']].describe()
overall_stats

           duration      avg_vote
count  41399.000000  41399.000000
mean     100.537163      5.801522
std       27.260962      1.403861
min       41.000000      1.000000
25%       90.000000      4.800000
50%       96.000000      5.900000
75%      107.000000      6.900000
max     1525.000000     10.000000

**df.count():** This method returns the number of non-null values in each DataFrame column. It can be used to count the number of non-null values in each column individually.

**df.value_counts():** This method returns the frequency counts of unique values in a Series. It is typically used on a single column of the DataFrame and is useful for analyzing the distribution of values within that column.

In [84]:
# Value Counts
df['genre'].value_counts()

genre
Drama              12003
Comedy              9225
Thriller            3701
Horror              2431
Action              2155
Documentary         2051
Adventure           1524
Western             1146
Animation           1076
Romantic             980
Sci-Fi               905
Biography            685
Fantasy              503
Crime                466
Musical              428
War                  405
Grotesque            243
Spy                  240
Noir                 238
Erotico              235
Sperimental          162
History              138
Mélo                 104
Super-hero            83
Mythology             66
Gangster              56
Biblical              38
Sport                  7
Short Movie            6
Stand-up Comedy        4
Name: count, dtype: int64

In [124]:
df['description']

movie_num
0        With two protruding front teeth, a slightly sl...
1        Samantha, not yet eighteen, leaves the comfort...
2        In the Australia of the pioneers, a boy and a ...
3        Five boys from Baltimore have a habit of meeti...
4        With a stratagem, the penniless and somewhat p...
                               ...
41394    Celeste is an attractive waitress in the forti...
41395    When Eleonora is downloaded to the altar, her ...
41396    A team building conference organized for a gro...
41397    Once Ok-Ju worked as a bodyguard and was one o...
41398    A great passionate of crime stories is trapped...
Name: description, Length: 41399, dtype: object

In [123]:
df.isnull().sum()

filmtv_id              0
title                  0
year                   0
genre                  0
duration               0
country               10
directors             34
actors              2127
avg_vote               0
critics_vote        4696
public_vote          194
total_votes         4696
description         1542
notes              22602
humor                  0
rhythm                 0
effort                 0
tension                0
erotism                0
length_category        0
old_new                0
title_year             0
dtype: int64

In [69]:
df['genre'].mode()[0]

'Drama'

In [70]:
df['avg_vote'].mean()

5.801521775888306

In [122]:
df['genre'].fillna(df['genre'].mode()[0],inplace=True)

In [125]:
df.duplicated().sum()

0

In [127]:
df.drop_duplicates(inplace=True)

In [128]:
df.to_csv('movies.csv')